write:
  _target_: langchain_aws.ChatBedrock
  model_id: global.anthropic.claude-opus-4-5-20251101-v1:0
  region_name: ${oc.env:AWS_DEFAULT_REGION,us-east-1}

code:
  _target_: langchain_aws.ChatBedrock
  model_id: global.anthropic.claude-opus-4-5-20251101-v1:0
  region_name: ${oc.env:AWS_DEFAULT_REGION,us-east-1}
