_target_: agenda.LocalAgenda

defaults:
  - _self_
  - logger: wandb # noop

checkpoint_path: "agenda-run3.pkl"
checkpoint_interval: 100
benchmark_codebase_time: 300
sort_every: 100
language: dafny

max_attempts: 10000
