_target_: agenda.LocalAgenda

defaults:
  - _self_
  - logger: wandb # noop

checkpoint_path: "agenda-framac-discovery.pkl"
checkpoint_interval: 10
benchmark_codebase_time: 300
sort_every: 100
language: framac

max_attempts: 10000
